const today = new Date();

const dateKey = offset => {
  const date = new Date(today);
  date.setDate(date.getDate() + offset);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
};

const isoOffset = days => {
  const date = new Date(today);
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

const DEMO_NOTE = 'Dado fictício criado exclusivamente para a demonstração do Fuply para a INNOVA Automation & Engenharia.';

export const INNOVA_DEMO_ACCOUNT = {
  id: 'demo-innova',
  name: 'INNOVA Automation & Engenharia · Demonstração',
  email: 'demo@innova.local',
  theme: 'dark',
  onboardingCompleted: true,
  onboarding: { goal: 'sales', selling: 'services' },
};

export const INNOVA_DEMO_TEAM = [
  { user_id: 'demo-innova', name: 'Comercial', role: 'owner' },
  { user_id: 'demo-innova-eng', name: 'Engenharia', role: 'member' },
  { user_id: 'demo-innova-dir', name: 'Diretoria', role: 'admin' },
];

export const INNOVA_DEMO_LEADS = [
  {
    id: 'innova-1',
    name: 'Marcelo Azevedo',
    company: 'Residência Alto Padrão · Jardim Europa',
    phone: '11910010001',
    value: 38000,
    status: 'Novo lead',
    origin: 'Site',
    assignedTo: 'demo-innova',
    nextContact: dateKey(0),
    nextContactTime: '09:30',
    nextAction: 'Qualificar escopo de automação residencial',
    notes: `${DEMO_NOTE} Interesse em automação de iluminação, climatização e persianas.`,
    createdAt: isoOffset(0),
    updatedAt: isoOffset(0),
    lastFollowupAt: null,
  },
  {
    id: 'innova-2',
    name: 'Carolina Mendes',
    company: 'Apartamento · Higienópolis',
    phone: '11910010002',
    value: 62000,
    status: 'Contatado',
    origin: 'Indicação',
    assignedTo: 'demo-innova',
    nextContact: dateKey(-1),
    nextContactTime: '15:00',
    nextAction: 'Retomar visita técnica e necessidades do projeto',
    notes: `${DEMO_NOTE} Projeto residencial com áudio ambiente, automação e rede Wi-Fi premium.`,
    createdAt: isoOffset(8),
    updatedAt: isoOffset(2),
    lastFollowupAt: isoOffset(2),
  },
  {
    id: 'innova-3',
    name: 'Ricardo Nogueira',
    company: 'Escritório Corporativo · Faria Lima',
    phone: '11910010003',
    value: 98000,
    status: 'Interessado',
    origin: 'Site',
    assignedTo: 'demo-innova-eng',
    nextContact: dateKey(1),
    nextContactTime: '11:00',
    nextAction: 'Agendar visita técnica para videoconferência e automação',
    notes: `${DEMO_NOTE} Ambientes corporativos com salas de reunião, videoconferência e controle integrado.`,
    createdAt: isoOffset(11),
    updatedAt: isoOffset(1),
    lastFollowupAt: isoOffset(1),
  },
  {
    id: 'innova-4',
    name: 'Fernanda Reis',
    company: 'Residência · Cidade Jardim',
    phone: '11910010004',
    value: 145000,
    status: 'Proposta enviada',
    origin: 'WhatsApp',
    assignedTo: 'demo-innova',
    nextContact: dateKey(0),
    nextContactTime: '16:00',
    nextAction: 'Confirmar análise da proposta completa',
    notes: `${DEMO_NOTE} Proposta de automação, sonorização, iluminação e infraestrutura elétrica.`,
    createdAt: isoOffset(18),
    updatedAt: isoOffset(3),
    lastFollowupAt: isoOffset(3),
  },
  {
    id: 'innova-5',
    name: 'André Moreira',
    company: 'Condomínio Residencial · Moema',
    phone: '11910010005',
    value: 185000,
    status: 'Negociação',
    origin: 'Indicação',
    assignedTo: 'demo-innova-dir',
    nextContact: dateKey(0),
    nextContactTime: '17:30',
    nextAction: 'Revisar escopo e condição comercial',
    notes: `${DEMO_NOTE} Negociação fictícia de infraestrutura, rede e integração de sistemas para áreas comuns.`,
    createdAt: isoOffset(24),
    updatedAt: isoOffset(1),
    lastFollowupAt: isoOffset(1),
  },
  {
    id: 'innova-6',
    name: 'Paula Vasconcelos',
    company: 'Clínica Corporativa · Itaim Bibi',
    phone: '11910010006',
    value: 76000,
    status: 'Negociação',
    origin: 'Site',
    assignedTo: 'demo-innova-eng',
    nextContact: dateKey(2),
    nextContactTime: '10:00',
    nextAction: 'Alinhar pontos técnicos antes do fechamento',
    notes: `${DEMO_NOTE} Rede Wi-Fi premium, elétrica, áudio e videoconferência.`,
    createdAt: isoOffset(20),
    updatedAt: isoOffset(2),
    lastFollowupAt: isoOffset(2),
  },
  {
    id: 'innova-7',
    name: 'Thiago Martins',
    company: 'Edifício Comercial · Pinheiros',
    phone: '11910010007',
    value: 54000,
    status: 'Interessado',
    origin: 'Google Maps',
    assignedTo: 'demo-innova-eng',
    nextContact: dateKey(3),
    nextContactTime: '14:30',
    nextAction: 'Solicitar documentos para projeto AVCB/CLCB',
    notes: `${DEMO_NOTE} Interesse em projeto de segurança contra incêndio e adequações elétricas.`,
    createdAt: isoOffset(5),
    updatedAt: isoOffset(1),
    lastFollowupAt: isoOffset(1),
  },
  {
    id: 'innova-8',
    name: 'Juliana Prado',
    company: 'Casa · Alto de Pinheiros',
    phone: '11910010008',
    value: 44000,
    status: 'Contatado',
    origin: 'Instagram',
    assignedTo: 'demo-innova',
    nextContact: dateKey(4),
    nextContactTime: '13:00',
    nextAction: 'Confirmar briefing de iluminação e sonorização',
    notes: `${DEMO_NOTE} Primeiro contato fictício para automação, iluminação e som ambiente.`,
    createdAt: isoOffset(3),
    updatedAt: isoOffset(1),
    lastFollowupAt: isoOffset(1),
  },
  {
    id: 'innova-9',
    name: 'Eduardo Leal',
    company: 'Residência · Morumbi',
    phone: '11910010009',
    value: 118000,
    saleValue: 112000,
    saleValueSource: 'confirmed',
    status: 'Fechado',
    origin: 'Indicação',
    assignedTo: 'demo-innova-dir',
    nextContact: '',
    nextContactTime: '',
    nextAction: '',
    notes: `${DEMO_NOTE} Venda fictícia fechada para demonstrar resultados e histórico.`,
    createdAt: isoOffset(37),
    updatedAt: isoOffset(4),
    soldAt: isoOffset(4),
    lastFollowupAt: isoOffset(4),
  },
  {
    id: 'innova-10',
    name: 'Renato Barros',
    company: 'Escritório · Vila Olímpia',
    phone: '11910010010',
    value: 47000,
    status: 'Perdido',
    origin: 'WhatsApp',
    assignedTo: 'demo-innova',
    nextContact: '',
    nextContactTime: '',
    nextAction: '',
    notes: `${DEMO_NOTE} Oportunidade fictícia encerrada para demonstrar o funil completo.`,
    createdAt: isoOffset(29),
    updatedAt: isoOffset(8),
    lastFollowupAt: isoOffset(8),
  },
];

export const INNOVA_DEMO_WHATSAPP = '11910019999';
