import React,{useMemo,useState}from'react';
import{AlertTriangle,CalendarClock,Check,ChevronRight,Clock3,MessageCircle,Plus,RefreshCw,Search,Target,UsersRound,X}from'lucide-react';
import'./leads.css';
const CLOSED=['Vendido','Perdido'];
const STATUSES=['Novo lead','Contatado','Interessado','Proposta enviada','Vendido','Perdido'];
const SCOPES=['Todos','Hoje','Atrasados','Próx. 7 dias','Sem próximo contato'];
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v||0));
const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const noon=v=>new Date(`${v}T12:00:00`);
const diff=v=>v?Math.round((noon(v)-noon(today()))/86400000):null;
const pretty=v=>{if(!v)return'Sem próximo contato';const d=diff(v);if(d===0)return'Hoje';if(d===1)return'Amanhã';if(d===-1)return'Ontem';if(d<-1)return`${Math.abs(d)} dias atrás`;return noon(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}).replace('.','')};
const full=v=>noon(v).toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'}).replace('.','');
const statusClass=s=>s.toLowerCase().replaceAll(' ','-');
function inScope(lead,scope){if(scope==='Todos')return true;const closed=CLOSED.includes(lead.status),d=diff(lead.nextContact);if(scope==='Sem próximo contato')return!lead.nextContact&&!closed;if(closed||!lead.nextContact)return false;if(scope==='Hoje')return d===0;if(scope==='Atrasados')return d<0;if(scope==='Próx. 7 dias')return d>0&&d<=7;return true}
export default function LeadsPage({leads,setLeads,openLead,openWhatsApp,onNewLead,updateLeadStatus}){
 const[query,setQuery]=useState(''),[status,setStatus]=useState('Todos'),[scope,setScope]=useState('Todos'),[rescheduling,setRescheduling]=useState(null),[schedule,setSchedule]=useState({date:'',time:'',action:''}),[toast,setToast]=useState('');
 const summary=useMemo(()=>{const active=leads.filter(l=>!CLOSED.includes(l.status)),dated=active.filter(l=>l.nextContact);return{overdue:dated.filter(l=>diff(l.nextContact)<0),today:dated.filter(l=>diff(l.nextContact)===0),week:dated.filter(l=>diff(l.nextContact)>0&&diff(l.nextContact)<=7),without:active.filter(l=>!l.nextContact)}},[leads]);
 const counts=useMemo(()=>Object.fromEntries(STATUSES.map(s=>[s,leads.filter(l=>l.status===s).length])),[leads]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return leads.filter(l=>!q||`${l.name} ${l.company} ${l.phone} ${l.origin} ${l.status} ${l.nextAction}`.toLowerCase().includes(q)).filter(l=>status==='Todos'||l.status===status).filter(l=>inScope(l,scope)).sort((a,b)=>a.nextContact&&b.nextContact?`${a.nextContact}${a.nextContactTime||''}`.localeCompare(`${b.nextContact}${b.nextContactTime||''}`):a.nextContact?-1:b.nextContact?1:a.createdAt&&b.createdAt?b.createdAt.localeCompare(a.createdAt):0)},[leads,query,status,scope]);
 const flash=t=>{setToast(t);window.setTimeout(()=>setToast(''),2200)};
 const changeStatus=(lead,next)=>{if(lead.status===next)return;updateLeadStatus(lead.id,next);flash(next==='Vendido'?`Confirme o valor final da venda de ${lead.name}.`:`${lead.name} atualizado para ${next}.`)};
 const complete=lead=>{const now=new Date().toISOString();setLeads(cur=>cur.map(l=>l.id===lead.id?{...l,nextContact:'',nextContactTime:'',nextAction:'',lastFollowupAt:now,updatedAt:now}:l));flash(`Follow-up de ${lead.name} concluído. O lead continua salvo.`)};
 const openReschedule=lead=>{setRescheduling(lead);setSchedule({date:lead.nextContact||today(),time:lead.nextContactTime||'',action:lead.nextAction||'Retornar contato'})};
 const quick=days=>{const d=new Date();d.setDate(d.getDate()+days);setSchedule(s=>({...s,date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}))};
 const save=event=>{event.preventDefault();if(!rescheduling||!schedule.date)return;setLeads(cur=>cur.map(l=>l.id===rescheduling.id?{...l,nextContact:schedule.date,nextContactTime:schedule.time,nextAction:schedule.action,updatedAt:new Date().toISOString()}:l));flash(`${rescheduling.name} reagendado para ${full(schedule.date)}.`);setRescheduling(null)};
 return <main className="main-content leads-page">
  <header className="leads-header"><div><span className="leads-kicker"><UsersRound size={14}/> Base de clientes</span><h1>Leads</h1><p>Todos os contatos em um só lugar, com follow-ups integrados.</p></div><button className="primary-button" onClick={onNewLead}><Plus size={18}/> Novo lead</button></header>
  <section className="leads-summary">
   <button className={`critical ${scope==='Atrasados'?'active':''}`} onClick={()=>setScope(scope==='Atrasados'?'Todos':'Atrasados')}><AlertTriangle size={18}/><span>Atrasados<strong>{summary.overdue.length}</strong></span></button>
   <button className={`today ${scope==='Hoje'?'active':''}`} onClick={()=>setScope(scope==='Hoje'?'Todos':'Hoje')}><CalendarClock size={18}/><span>Para hoje<strong>{summary.today.length}</strong></span></button>
   <button className={`upcoming ${scope==='Próx. 7 dias'?'active':''}`} onClick={()=>setScope(scope==='Próx. 7 dias'?'Todos':'Próx. 7 dias')}><Clock3 size={18}/><span>Próx. 7 dias<strong>{summary.week.length}</strong></span></button>
   <button className={`missing ${scope==='Sem próximo contato'?'active':''}`} onClick={()=>setScope(scope==='Sem próximo contato'?'Todos':'Sem próximo contato')}><Target size={18}/><span>Sem próximo contato<strong>{summary.without.length}</strong></span></button>
  </section>
  <section className="leads-directory">
   <div className="leads-directory-top"><label className="leads-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nome, empresa, WhatsApp ou ação"/></label><span className="leads-result-count">{filtered.length} de {leads.length} leads</span></div>
   <div className="leads-scope-tabs">{SCOPES.map(s=><button key={s} className={scope===s?'active':''} onClick={()=>setScope(s)}>{s}</button>)}</div>
   <div className="leads-status-tabs"><button className={status==='Todos'?'active':''} onClick={()=>setStatus('Todos')}>Todos <b>{leads.length}</b></button>{STATUSES.map(s=><button key={s} className={status===s?'active':''} onClick={()=>setStatus(s)}>{s} <b>{counts[s]}</b></button>)}</div>
   <div className="leads-desktop-table-wrap"><table className="leads-table"><thead><tr><th>Lead</th><th>Status</th><th>Origem</th><th>Valor</th><th>Próximo contato</th><th>Próxima ação</th><th>Ações</th></tr></thead><tbody>{filtered.map(lead=><tr key={lead.id} tabIndex={0} onClick={()=>openLead(lead)} onKeyDown={e=>e.key==='Enter'&&openLead(lead)}>
    <td><div className="lead-contact-cell"><div className="leads-avatar">{lead.name.slice(0,2).toUpperCase()}</div><div><strong>{lead.name}</strong><span>{lead.company||'Sem empresa'}</span></div></div></td>
    <td onClick={e=>e.stopPropagation()}><select className="leads-status-select" value={lead.status} onChange={e=>changeStatus(lead,e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></td>
    <td><span className="lead-origin">{lead.origin||'Outro'}</span></td><td><strong className="leads-value">{money(lead.status==='Vendido'?lead.saleValue:lead.value)}</strong></td>
    <td><span className={`leads-next ${lead.nextContact?'':'muted'} ${diff(lead.nextContact)<0?'overdue':''}`}><CalendarClock size={14}/>{pretty(lead.nextContact)}{lead.nextContactTime?` · ${lead.nextContactTime}`:''}</span></td><td>{lead.nextAction||'—'}</td>
    <td onClick={e=>e.stopPropagation()}><div className="lead-row-actions"><button className="leads-whatsapp" onClick={()=>openWhatsApp(lead)} title="WhatsApp"><MessageCircle size={15}/></button>{!CLOSED.includes(lead.status)&&<button className="lead-mini-action" onClick={()=>openReschedule(lead)} title="Reagendar"><RefreshCw size={15}/></button>}{lead.nextContact&&!CLOSED.includes(lead.status)&&<button className="lead-mini-action done" onClick={()=>complete(lead)} title="Concluir follow-up"><Check size={15}/></button>}<button className="lead-open-button" onClick={()=>openLead(lead)}><ChevronRight size={16}/></button></div></td>
   </tr>)}</tbody></table></div>
   <div className="leads-mobile-list">{filtered.map(lead=><article className="lead-directory-card" key={lead.id}><div className="lead-directory-card-top"><div className="lead-contact-cell"><div className="leads-avatar">{lead.name.slice(0,2).toUpperCase()}</div><div><strong>{lead.name}</strong><span>{lead.company||'Sem empresa'}</span></div></div><span className={`leads-status status-${statusClass(lead.status)}`}>{lead.status}</span></div><div className="lead-directory-card-meta"><span><CalendarClock size={14}/>{pretty(lead.nextContact)}</span><span><Target size={14}/>{lead.nextAction||'Sem próxima ação'}</span></div><div className="lead-directory-card-bottom"><strong>{money(lead.status==='Vendido'?lead.saleValue:lead.value)}</strong><div><button className="mobile-whatsapp" onClick={()=>openWhatsApp(lead)}><MessageCircle size={15}/></button>{!CLOSED.includes(lead.status)&&<button className="mobile-open" onClick={()=>openReschedule(lead)}><RefreshCw size={15}/></button>}{lead.nextContact&&!CLOSED.includes(lead.status)&&<button className="mobile-open" onClick={()=>complete(lead)}><Check size={15}/></button>}<button className="mobile-open" onClick={()=>openLead(lead)}><ChevronRight size={15}/></button></div></div></article>)}</div>
   {!filtered.length&&<div className="leads-empty"><UsersRound size={30}/><h2>Nenhum lead encontrado</h2><p>Ajuste os filtros ou adicione um novo contato.</p></div>}
  </section>
  {rescheduling&&<div className="modal-backdrop" onMouseDown={()=>setRescheduling(null)}><section className="modal reschedule-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><h2>Reagendar follow-up</h2><p>{rescheduling.name} · {rescheduling.company||'Sem empresa'}</p></div><button className="icon-button" onClick={()=>setRescheduling(null)}><X size={20}/></button></div><div className="quick-dates"><span>Atalhos</span><button onClick={()=>quick(1)}>Amanhã</button><button onClick={()=>quick(3)}>+3 dias</button><button onClick={()=>quick(7)}>+7 dias</button></div><form className="lead-form" onSubmit={save}><label><span>Data *</span><input required type="date" min={today()} value={schedule.date} onChange={e=>setSchedule({...schedule,date:e.target.value})}/></label><label><span>Horário</span><input type="time" value={schedule.time} onChange={e=>setSchedule({...schedule,time:e.target.value})}/></label><label className="full"><span>Próxima ação</span><input value={schedule.action} onChange={e=>setSchedule({...schedule,action:e.target.value})}/></label><div className="modal-actions full"><button type="button" className="secondary-button" onClick={()=>setRescheduling(null)}>Cancelar</button><button className="primary-button"><RefreshCw size={16}/> Reagendar</button></div></form></section></div>}
  {toast&&<div className="leads-toast"><Check size={16}/>{toast}</div>}
 </main>;
}
